### ISSUE TITLE
Please resubmit PR

### ISSUE THREAD

**Issue by rafaelsales** [shreeramneupane/remotelock#2]
@shreeramneupane Hi, we forgot to deactivate a github action that is only supposed to be active in our template repository.
Could you please:
1. Remove https://github.com/shreeramneupane/remotelock/blob/master/.github/workflows/lockdown.yml directly in your master branch.
2. Resubmit your solution PR so that it's not closed this time.

Thank you!!

**Comment by shreeramneupane** [comment]
@rafaelsales done
